"""Generate Figure 6 (fig:pool_size) for the MICRO paper.
2x2 grid: each panel shows one objective metric with SA vs SAEO, normalized to N=1.
"""
import os
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

plt.rcParams.update({
    'font.size': 10,
    'font.family': 'serif',
    'axes.labelsize': 11,
    'axes.titlesize': 11,
    'legend.fontsize': 9,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'axes.grid': True,
    'grid.alpha': 0.25,
    'grid.linewidth': 0.5,
})

SA_COLOR = '#2171b5'
SAEO_COLOR = '#cb181d'

_HERE = os.path.dirname(os.path.abspath(__file__))
# NOTE: this is the LEGACY Figure-6 plotter. The paper's Figure 8 is produced by
# generate_paper_fig6_chain.py. Its input (summary_pivot.csv) is NOT shipped in the
# artifact, so this script is kept for reference only.
CSV = os.environ.get('FENGSHUI_FIG6_CSV',
                     os.path.join(_HERE, '..', 'archgym_results', 'figures', 'summary_pivot.csv'))
OUT_DIR = os.environ.get('FENGSHUI_FIG_OUT', os.path.join(_HERE, '..', 'figures'))

if not os.path.exists(CSV):
    raise SystemExit(
        f'[fig6-legacy] input not found: {CSV}\n'
        '  This legacy plotter is not part of the artifact-evaluation path and its\n'
        '  input is not shipped. The paper Figure 8 is generated by\n'
        '  generate_paper_fig6_chain.py -- run that instead.')

df = pd.read_csv(CSV)
ns = df['N'].values

# Define 4 panels: (title, SA column, SAEO column)
panels = [
    ('Energy',            'Energy / SA',      'Energy / SAEO'),
    ('Energy $\\times$ Cost', 'Energy×Cost / SA', 'Energy×Cost / SAEO'),
    ('EDP',               'EDP / SA',         'EDP / SAEO'),
    ('EDP $\\times$ Cost',    'EDP×Cost / SA',    'EDP×Cost / SAEO'),
]

fig, axes = plt.subplots(2, 2, figsize=(7, 5.5))
axes = axes.flatten()

for idx, (title, sa_col, saeo_col) in enumerate(panels):
    ax = axes[idx]
    sa_vals = df[sa_col].values
    saeo_vals = df[saeo_col].values

    # Normalize to N=1
    sa_norm = sa_vals / sa_vals[0]
    saeo_norm = saeo_vals / saeo_vals[0]

    ax.plot(ns, sa_norm, '-o', color=SA_COLOR, label='SA',
            markersize=4, linewidth=1.5, markeredgewidth=0.5, markeredgecolor='white')
    ax.plot(ns, saeo_norm, '-s', color=SAEO_COLOR, label='SAEO',
            markersize=4, linewidth=1.5, markeredgewidth=0.5, markeredgecolor='white')

    # Dashed line at N=8
    ax.axvline(x=8, color='gray', linestyle='--', linewidth=0.8, alpha=0.7)
    if idx == 0:
        ax.text(8.3, 0.95, 'Our Chiplet\nPool', fontsize=7.5,
                fontstyle='italic', fontweight='bold', va='top', color='#333333')

    ax.set_xlabel('Number of Chiplets')
    ax.set_ylabel('Normalized Value')
    ax.set_title(title)
    ax.set_xticks([1, 4, 8, 12, 16])
    ax.set_xlim(0.5, 16.5)
    ax.set_ylim(0, 1.05)
    ax.legend(loc='upper right', framealpha=0.9)

plt.tight_layout(h_pad=1.0, w_pad=0.8)
os.makedirs(OUT_DIR, exist_ok=True)

out_pdf = os.path.join(OUT_DIR, 'num_chiplet_sweep.pdf')
out_png = os.path.join(OUT_DIR, 'num_chiplet_sweep.png')
plt.savefig(out_pdf)
plt.savefig(out_png)
plt.close()
print(f'Saved {out_pdf}')
print(f'Saved {out_png}')
